---
- name: Install Cockpit dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - cockpit
    - cockpit-podman

- name: Enable and start Cockpit service
  ansible.builtin.systemd:
    name: cockpit
    state: started
    enabled: yes