version: '3.7'

services:
  ubooquity:
    image: linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /media/user/T7/ubooquity/books:/books
      - /media/user/T7/ubooquity/comics:/comics
      - /media/user/T7/ubooquity/config:/config
    ports:
      - 5001:5001
      - 5002:5002
    restart: unless-stopped
