version: '3'

services:
  db:
    image: mariadb
    volumes:
      - /media/user/T7/nextcloud/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - /media/user/T7/nextcloud/data:/var/www/html/data
      - /media/user/T7/nextcloud/config:/var/www/html/config
    depends_on:
      - db
    restart: unless-stopped
