version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: Europe/Paris
      WEBPASSWORD: my-secret-pw
    volumes:
      - /meta/user/T7/pihole/etc-pihole/:/etc/pihole/
      - /meta/user/T7/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
